name: event_manager
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_storage: ^2.1.1
  get: ^4.6.6
  firebase_core: ^3.7.0
  google_sign_in: ^6.1.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.6


  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.0

  intl: ^0.19.0
  google_fonts: ^6.2.1
  sqflite: ^2.4.1
  date_picker_timeline: ^1.2.6
  flutter_staggered_animations: ^1.1.1

  image_picker: ^0.8.7
  video_player: ^2.5.3
  file_picker: ^5.3.1
  visibility_detector: ^0.4.0+2
  url_launcher: ^6.2.6

  share_plus: ^10.1.2

  pdf: ^3.10.4
  path: ^1.8.3
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  open_filex: ^4.3.2

  shared_preferences: ^2.4.0
  local_auth: ^2.1.7
  connectivity_plus: ^6.1.3

  flutter_colorpicker: ^1.0.3
  flutter_pdfview: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/reminder.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
